networks:
  rinha-network:
    driver: bridge

services:
  app1:
    build: ./payment-processor
    environment:
      - ConnectionStrings__Default=Host=db;Database=rinha;Username=postgres;Password=postgres;Pooling=true;Minimum Pool Size=5;Maximum Pool Size=100
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_NAMEAPP=default
    depends_on:
      db:
        condition: service_healthy
    networks:
      rinha-network:
        aliases:
          - payment-processor-default
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: 90m

  app2:
    build: ./payment-processor
    environment:
      - ConnectionStrings__Default=Host=db;Database=rinha;Username=postgres;Password=postgres;Pooling=true;Minimum Pool Size=5;Maximum Pool Size=100
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_NAMEAPP=fallback
    depends_on:
      db:
        condition: service_healthy
    networks:
      rinha-network:
        aliases:
          - payment-processor-fallback
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: 90m

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rinha
    command: [
      "postgres",
      "-c", "max_connections=100",
      "-c", "shared_buffers=128MB",
      "-c", "effective_cache_size=256MB",
      "-c", "maintenance_work_mem=64MB",
      "-c", "checkpoint_completion_target=0.9",
      "-c", "wal_buffers=16MB",
      "-c", "default_statistics_target=100",
      "-c", "random_page_cost=1.1",
      "-c", "effective_io_concurrency=200",
      "-c", "work_mem=4MB",
      "-c", "deadlock_timeout=1s",
      "-c", "lock_timeout=30s"
    ]
    restart: unless-stopped
    networks:
      - rinha-network
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d rinha"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 90m

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly no --maxmemory 100mb --maxmemory-policy allkeys-lru --protected-mode no
    restart: unless-stopped
    networks:
      - rinha-network
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 50m

  nginx:
    image: nginx:latest
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 30m

volumes:
  db_data:
  redis_data:
